# Generated by Django 4.2.16 on 2025-01-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='userinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstApp.userinfo'),
        ),
    ]
